### ISSUE TITLE
Create a new order based procflow

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#257]
# Requested Update

Milestone:
https://github.com/NRLMMD-GEOIPS/geoips/milestone/13

### Description
Create a new procflow called `order_based` and a associated product and product_defaults families, also called `order_based`. 

The new `order_based` product and product_defaults families will have the same metadata as current families, but their spec will be an array instead of a mapping. Each of the array's elements will specify an interface, a plugin for that interface, and its arguments. During processing, these plugins will be applied in the order in which they are defined.

As an example, the current 19H product_defaults plugin looks like this:
```yaml
interface: product_defaults
family: interpolator_algorithm_colormapper
name: 19H
docstring: |
  The 19H product defaults configuration.
spec:
  interpolator:
    plugin:
      name: interp_gauss
      arguments:
        sigmaval: 25000
  algorithm:
    plugin:
      name: single_channel
      arguments:
        output_data_range: [125, 300]
        min_outbounds: crop
        max_outbounds: crop
        norm: null
        inverse: null
  mtif_type: pmw
  colormapper:
    plugin:
      name: pmw_37H
      arguments:
        data_range: [125, 300]
```

When converted to the new format, it would look like this:
```yaml
interface: product_defaults
family: order_based
name: 19H
docstring: |
  The 19H product defaults configuration.
spec:
  mtif_type: pmw  # Unsure about this part...
  steps:
    - interpolator:
        plugin:
          name: interp_gauss
          arguments:
            sigmaval: 25000
    - algorithm:
        plugin:
          name: single_channel
          arguments:
            output_data_range: [125, 300]
            min_outbounds: crop
            max_outbounds: crop
            norm: null
            inverse: null
    - colormapper:
        plugin:
          name: pmw_37H
          arguments:
            data_range: [125, 300]
```

Given the above product_defaults definition procflow will perform actions in the following order

- Read data
- Loop through the plugins in the order that they are provided in the `steps` array
  - interpolator
  - algorithm
  - colormapper
- Prepare and write output (probably need to flesh this out more based on `single_source`)

### Background and Motivation
The current `single_source` procflow relies on product families to determine the processing order. This is somewhat inflexible as it doesn't allow certain operations (e.g. applying two algorithms to data in a single procflow). Additionally, some of the current product families do not work (e.g. `algorithm_interpolator_colormapper`). Lastly, `single_source` is confusing and difficult to track data through, making it difficult to fix the broken product families.

Implementing the `order_based` will allow products to be more complex while reducing the number of required product families. It will also result in a less complex procflow.

### Alternative Solutions
Just try to fix the `single_source` procflow. This looks like a difficult task...
  
### Tasks
This is a complex issue that will likely be under development for a while. As such, I expect that this task list will grow and change in time. For now:
* [ ] #423 
* [ ] #433 
* [ ] #425 
* [ ] Construct a schema for the `order_based` product_defaults family
  * [ ] Write unit tests for the new schema
* [ ] Update the product schema to include the ability to use the new product_defaults family
  * [ ] Write a few example products that we can use for testing later.
* [ ] #533
  * [ ] Create a list of all functions called in `single_source`
  * [ ] Determine which functions are used/unused
  * [ ] Determine and make note of the following for each function:
    - What it does
    - What its inputs should be and any required information about the state they should be in (e.g. pre-registered, algorithm already applied, etc)
    - What it outputs including information like number of dimensions, number of elements, etc.
  * [ ] Determine which functions are needed for our application.
* [ ] Create a new module that imports and exposes all of the functions that we will need for the new procflow (in anticipation of reorganizing later)
* [ ] Use the newly exposed functions to write the new procflow
* [ ] #892
* [ ] #893 
* [ ] #894 
* [ ] #896 
* [ ] #897 

#### Functions used by `single_source`
get_area_defs_from_command_line_args()
geoips.sector_uitls.utils
get_static_area_defs_for_xarray()
get_tc_area_defs_for_xarray()
get_trackfile_area_defs()
filter_area_defs_actual_time()
pyresample.geometry
SwathDefinition()
process_xarray_dict_to_output_format()
pad_area_definition()
geoips.sector_utils.utils
is_sector_type()
copy_sector_info()
geoips.plugins.modules.sector_spec_generators.center_coordinates
call()
verify_area_def()
process_sectored_data_output()
get_alg_xarray()
plot_data()
remove_unsupported_kwargs()
output_all_metadata()
add_filename_extra_field()
get_output_filenames()
get_filename()
Functions imported:
geoips.commandline.args
check_command_line_args()
datetime.datetime
utcnow()
geoips_db.dev.postgres_database
get_db_writer()
geoips.interfaces —>
algorithms
colormappers
filename_formatters
interpolators
output_formatters
get_plugin()
products
get_plugin
readers
get_plugin()
sector_adjusters
get_plugin()
geoips.utils.memusg
print_mem_usage()
geoips.dev.product
get_required_variables()
get_requested_datasets_for_variables()
get_covg_from_product()
get_covg_args_from_product()
geoips.xarray_utils.data
sector_xarrays()
geoips.dev.output_config()
get_filename_formatters()
get_filename_formatter_kwargs()
get_output_formatter()
get_output_formatter_kwargs()
get_metadata_filename_formatter()
get_metadata_filename_formatter_kwargs()
get_metadata_output_formatter()
get_metadata_output_formatter_kwargs()
get_minimum_coverage()
geoips.filenames.duplicate_files
remove_duplicates()
geoips.geoips_utils
find_entry_point()
output_process_times()
copy_standard_metadata()
geoips.sector_utils.utils
filter_area_defs_actual_time()
is_dynamic_sector()
logging
getLogger()
error()
info()
xarray
Functions not used:
combine_filename_extra_fields()
print_area_def()

**Comment by evrose54** [comment]
Here is a document describing the state of single_source procflow as it currently stands.
[Single Source Digest.pdf](https://github.com/NRLMMD-GEOIPS/geoips/files/13982356/Single.Source.Digest.pdf)

**Comment by jsolbrig** [comment]
Something to consider as we do the order-based procflow is whether we should move the responsibility for interpolating multiple resolutions of data onto the interpolator plugins. Currently, looping over multiple data resolutions is handled by the single_source procflow (at least for the `interpolator_algorithm_colormapper` product family). It seems logical that the interpolators should be able to smartly loop over the resolutions and interpolate them all appropriately.

**Comment by evrose54** [comment]
Here's an idea of how to include a reader and an output formatter as part of the product definition
```yaml
interface: product_defaults
family: order_based
name: Infrared
docstring: |
  The Infrared product_defaults configuration.
spec:
  with: abi_netcdf # (reader name)
  apply:
    - algorithm:
        plugin:
          name: single_channel
          arguments:
            output_data_range: [-90.0, 30.0]
            input_units: Kelvin
            output_units: celsius
            min_outbounds: crop
            max_outbounds: crop
            norm: null
            inverse: null
    - mtif_type: ir # (unsure about this part)
    - colormapper:
        plugin:
          name: Infrared
          arguments:
            data_range: [-90.0, 30.0]
    - interpolator:
        plugin:
          name: interp_nearest
          arguments: {}
  as: imagery_annotated # (output_formatter name)
```

Where you could overwrite the spec portions of the product_defaults in the product file or the portions of the product in the procflow bash script if desired. Filenames would be supplied in the procflow bash script as is done currently.

**Comment by jsolbrig** [comment]
@evrose54 I like the thought and would like to talk more about it to see what you're thinking with it. At first glance, I'm wondering if it would complicate some of what I'm hoping to do, but maybe I'd feel differently about it if we talk about it some.

**Comment by srikanth-kumar** [comment]
This issue can be closed after @jsolbrig and @evrose54 confirm it.

**Comment by jsolbrig** [comment]
This can be closed. It has been superseded by several other issues and PRs relating to the OBP.
