### ISSUE TITLE
Create products for each possible product family handled by the single_source procflow

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#423]
# Task

### Description
Create a set of products for every available product family that is handled by single_source procflow. Attempt to run each of these to determine which work and which don't.

A quick look at the code finds these available product families:
- unsectored_xarray_dict_to_output_format
- sectored_xarray_dict_to_output_format
- unsectored_xarray_dict_area_to_output_format
- algorithm_colormapper
- algorithm_interpolator_colormapper
- algorithm
- interpolator

This looks pretty incomplete to me, but maybe that's actually it!

### Background and Motivation
In order to determine which portions of code are used and which are not, we need to run data through every possible path within the single_source procflow.

### Code to demonstrate issue
*  [ IF APPROPRIATE: Can include steps here to identify/demonstrate bug fix or desired feature ]

### Checklist for Completion
* [ ] Identify all possible product families in single_source
* [ ] Create a product for each family
* [ ] Create a test script for each family
* [ ] Test each family to determine whether it is able to produce an output file and whether that output file appears to be appropriate

**Comment by evrose54** [comment]
@jsolbrig I think this is the complete list of available product families; I could be wrong, but I'm assuming if they're not listed under the products schema, then they aren't a valid family.

<img width="366" alt="Screenshot 2024-01-19 at 1 09 04 PM" src="https://github.com/NRLMMD-GEOIPS/geoips/assets/62626811/60741787-f21e-481e-b640-65bfdea771e9">

**Comment by jsolbrig** [comment]
I'm not sure if they all actually work. It will be a good idea to get a handle on which do and don't work. 

The good news is that it looks like we should be able to replicate all of these relatively easily in the order-based procflow while allowing the possibility for other configurations too.

**Comment by evrose54** [comment]
See this [branch](https://github.com/NRLMMD-GEOIPS/geoips/tree/423-test-all-product-families) for the current status of this issue. There was a bug found when creating this issue, which you can see in [insert new issue here].

**Comment by mindyls** [comment]
I think it will be great to have these added, both for order based procflow devlopment, and for documentation NOW for people that want to use geoips with these various product families.  So, adding test scripts and documentation for these families would be GREAT.
