### ISSUE TITLE
Incoming Breaking Changes to the CLI

### ISSUE THREAD

**Issue by evrose54** [NRLMMD-GEOIPS/geoips#474]
# Requested Update

### Description
PR #433 will introduce changes into how product plugins are stored via the plugin registry. Instead of a tuple-based naming structure ``(source_name, product_name)``, we will now store plugins via ``source_name.product_name``. Accessing these plugins (Ie. via ``products.get_plugin`` will still occur in the same manner (``products.get_plugin("abi", "Infrared")``), however conversion is done automatically to a ``source_name.product_name`` string so we can access the plugin accordingly. These changes will break some portions of the CLI that interact with the products interface and will need to be updated accordingly.

### Background and Motivation
This issue stems from the creation of the CLI and the breaking changes that will be ingested via the #433 PR. To fix this, we'll need to address these changes in this order.
  - Merge in Initial CLI PR #444 
  - Merge in CLI Stage 2 PR #465 
  - Create New PR Branched off of Main, merge #433 into this new branch
    - Update this branch to fix breaking changes
  - Merge this updated PR into main
  - Remove #433 PR as those changes will have been merged in the previous PR

### Alternative Solutions
There are no alternative solutions for this. We either don't merge #433 and leave the code as is or make the changes as listed above.

### Code to demonstrate issue
See #465 and #433 and look how the changes to products in the plugin registry will break parts of the CLI.

### Checklist for Completion
* [ ] Merge in Initial CLI PR #444 
* [ ] Merge in CLI Stage 2 PR #465 
* [ ] Create New PR Branched off of Main, merge #433 into this new branch
* [ ] Update this branch to fix breaking changes
* [ ] Merge this updated PR into main
* [ ] Remove #433 PR as those changes will have been merged in the previous PR

**Comment by jsolbrig** [comment]
This PR will likely get closed without merging. @evrose54 will link to an issue that describes what needs to be done here, then will either close this PR and create a new one or modify this PR to match what is needed.

The current issue for this is #474.

**Comment by jsolbrig** [comment]
This can be closed as done.
